{% set name = "cyvlfeat" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e86633fb5687cfe1b5ef707b1eb618174070ca09a2b62aad7d3d8ad2a9de5562

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}

  host:
    - python
    - setuptools
    - pip
    - vlfeat
    - scipy
    - cython                                 # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  run:
    - python
    - setuptools
    - {{ pin_compatible('vlfeat', min_pin='x.x.x', max_pin='x.x.x') }}
    - {{ pin_compatible('numpy') }}
    - scipy

test:
  imports:
    - cyvlfeat.sift.sift
    - cyvlfeat.sift.dsift
    - cyvlfeat.fisher.fisher
    - cyvlfeat.hog.hog
    - cyvlfeat.kmeans.kmeans
    - cyvlfeat.generic.generic

about:
  home: https://github.com/menpo/cyvlfeat
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A Python (cython) wrapper of the VLFeat library

extra:
  recipe-maintainers:
    - patricksnape
