{% set name = "cyvlfeat" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f6c315075d4bde8d6b14dcab32d84c315e40304de2c52894bcaed11c68bd58ce

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - python
    - setuptools
    - pip
    - numpy
    - cython
    - vlfeat
    - scipy

  run:
    - python
    - {{ pin_compatible('vlfeat', min_pin='x.x.x', max_pin='x.x.x') }}
    - {{ pin_compatible('numpy') }}
    - scipy

test:
  imports:
    - cyvlfeat.sift.sift
    - cyvlfeat.sift.dsift
    - cyvlfeat.fisher.fisher
    - cyvlfeat.hog.hog
    - cyvlfeat.kmeans.kmeans
    - cyvlfeat.generic.generic

about:
  home: https://github.com/menpo/cyvlfeat
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A Python (cython) wrapper of the VLFeat library

extra:
  recipe-maintainers:
    - patricksnape
