travis:
  secure:
    BINSTAR_TOKEN: g54ugwk8/cxeIz6F9UjieGRjj9csa5ZWAQvsJxAW+990dObRIloTDD1eK7V1tvaIP8G9BZujAFOOBlwcp/ConrF6yAVb3FUlZ8ZKI+i5zQTvdyd72aH8RvUVzYAfRp5HVBLdsdrQhsFzmBvFMKM5gFmqRpW9R5h4dv5bg1Eg3WHDjyNO8h0z4Ms6Iy9YLrbEsRLrN1Z+u88kCdIt6+JCuBmQ3BE+JIul58O/RaWtxaDJewLZttAjILJhIJQMl/pIrpTNHQ0IFDXdsNsxjV6kaRX5Gd7ur0PEGuvXmV7lgMN6O+u0C2O2FIBTowoDOTiB76DudnrS3OHDPan7ciJlcxbvkM42HgR9LnmDB1L1ZT+YMOHnb5beyStu/DBuDWFnB9NRgudtPogs43moKoMWE+1JzC/HPwxV3/3HSYJrLsj8m7ZAilrL370ayBJl7yi6JxdtCpn9CWdkWCQ4J2xizoDeFnQwXWDsIFlTxy0ABfiWbkHdtHh/C4QfrUnHeIE5fa0v8Aas0J/Cg1Slr3QOaXSabwTqh1lLcjA+7f2CvUu0BBgSl1nVIi2vfhIVzwWMQLK1scPMPnU/nGDxRxjGxkBCbFjJSSgWyCnQL+W6+7o08oj2YnostbxGsPeIiT0OkkRYEsKHdIcMpoNqX91EtWYur35p761gDPY7Wga9d+M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
